export const ActionTypes = {
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCT",
    ON_CHANGE_LAYOUT2: "ON_CHANGE_LAYOUT2",
    ON_CHANGE_LAYOUT4: "ON_CHANGE_LAYOUT4",
    GET_ALL_CARS:"GET_ALL_CARS",
    GET_PRODUCT:"GET_PRODUCT",
}

export const AccountTypes = {
    LOG_IN:"LOG_IN",
    REGISTER_ACCOUNT:"REGISTER_ACCOUNT",
    RESTART_STATUS: "RESTART_STATUS"
}