export const ActionTypes = {
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCT",
    ON_CHANGE_LAYOUT2: "ON_CHANGE_LAYOUT2",
    ON_CHANGE_LAYOUT4: "ON_CHANGE_LAYOUT4",
    GET_ALL_CARS:"GET_ALL_CARS",
    GET_PRODUCT:"GET_PRODUCT",
    ADD_ORDER:"ADD_ORDER",
    RESTART_STATUS_ORDER:"RESTART_STATUS_ORDER",
    DELETE_PRODUCT_ORDERED:"DELETE_PRODUCT_ORDERED",
    EDIT_QUANTITY:"EDIT_QUANTITY"
}

export const AccountTypes = {
    LOG_IN:"LOG_IN",
    REGISTER_ACCOUNT:"REGISTER_ACCOUNT",
    RESTART_STATUS: "RESTART_STATUS",
    LOG_OUT:"LOG_OUT",
}

export const AdminTypes = {
    ANALYTIC_PRODUCTS : "ANALYTIC_PRODUCTS",
    UPDATE_INFO_USER:"UPDATE_INFO_USER",
    DELETE_USER:"DELETE_USER",
}